// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

/** dotenv does not expand ${VAR} inside .env — build the URL here from POSTGRES_* */
function postgresUrlFromEnv(): string {
  const direct = process.env['POSTGRES_URL'];
  if (direct && !direct.includes('${')) {
    return direct;
  }
  const user = encodeURIComponent(process.env['POSTGRES_USER'] ?? 'postgres');
  const password = encodeURIComponent(process.env['POSTGRES_PASSWORD'] ?? '');
  const host = process.env['POSTGRES_HOST'] ?? 'localhost';
  const port = process.env['POSTGRES_PORT'] ?? '5432';
  const database = process.env['POSTGRES_DB'] ?? 'postgres';
  return `postgresql://${user}:${password}@${host}:${port}/${database}`;
}

// eslint-disable-next-line @typescript-eslint/no-unsafe-call
export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: postgresUrlFromEnv(),
  },
});
